### ISSUE TITLE
Бот сообщество не отвечает в беседах

### ISSUE THREAD

**Issue by andrewsmith1551** [ekonda/sketal#125]
Пожалуйста, не забудьте внимательно прочитать README.md и всё настроить точно как в инструкциях. Попробуйте ещё раз проверить введённые данные, подождите немного. Убедитесь, что у вас есть доступ к интернету, vk.com.

#### Что случилось? В чём ошибка?
Бот-сообщество не отвечает людям в беседах, но в ЛС работает нормально. 
Бот-пользователь везде работает нормально.
Ошибок нет.
Доступ ко всей переписке давал, админку тоже давал. Не помогает.

#### Как повторить эту ошибку? (код, который вызвал ошибку, настройки)
-

**Comment by michaelkrukov** [comment]
Sketal не разработан с учётом бесед, и не проверялся в них.

**Comment by andrewsmith1551** [comment]
"Бот для ВКонтакте. Беседы / группы / развлечения. "
